### ISSUE TITLE
tartufo pre-commit fails on empty repo

### ISSUE THREAD

**Issue by wayneashleyberry** [godaddy/tartufo#147]
## 🐛 Bug Report

```
Traceback (most recent call last):
  File "/usr/local/bin/tartufo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tartufo/commands/pre_commit.py", line 20, in main
    issues = scanner.scan()
  File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 258, in scan
    for chunk in self.chunks:
  File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 518, in chunks
    self._repo.head.commit, create_patch=True, R=True
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 197, in _get_commit
    obj = self._get_object()
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 190, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 132, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 181, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 164, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/main' does not exist
```

## To Reproduce

I'm using a global pre-commit hook.

```
mkdir /path/to/my/centralized/hooks
cd /path/to/my/centralized/hooks
touch pre-commit
echo '#!/bin/sh' >> pre-commit
echo 'tartufo pre-commit' >> pre-commit
chmod +x pre-commit
git config --global core.hooksPath /path/to/my/centralized/hooks
```

Initialise a new repo and create an empty commit.

```
mkdir foo
cd foo
git init
git commit -m 'init' --allow-empty
```

## Expected Behavior

New or empty repo's should not report an error.

## Environment

```

                 -/+:.          wayne@Waynes-iMac
                :++++.          OS: 64bit Mac OS X 10.15.7 19H15
               /+++/.           Kernel: x86_64 Darwin 19.6.0
       .:-::- .+/:-``.::-       Uptime: 12d 2m
    .:/++++++/::::/++++++/:`    Packages: 168
  .:///////////////////////:`   Shell: fish 3.1.2
  ////////////////////////`     Resolution: 6400x3600
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Disk: 11G / 1.0T (2%)
  osssssssssssssssssssssssso/`  CPU: Intel Core i7-10700K @ 3.80GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: AMD Radeon Pro 5500 XT
   `ossssssssssssssssssssss/    RAM: 16221MiB / 32768MiB
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-
```

```
$ python3 --version
Python 3.8.2
```

```
$ tartufo -V
tartufo, version 2.0.2
```

**Comment by tarkatronic** [comment]
Hi @wayneashleyberry, thanks for reporting this! This is an interesting error, and somewhat makes sense with how this tool works. Given that this is such a rare corner case and easily worked around (by skipping commit hooks) I'm not sure how much of a priority we want to make this at the moment.

I do want to be certain that we get this fixed with the new backend implementation in #122 though. Unfortunately that is somewhat on hold at the moment due to https://github.com/libgit2/pygit2/issues/1024

All that said, if anybody feels like tackling this, contributions are always welcome!

**Comment by dclayton-godaddy** [comment]
@wayneashleyberry I'm sure you solved this by now, in case you haven't. I would:
1. disable pre-commit
2. create and push a commit (maybe with README.md)
3. enable pre-commit and resume

**Comment by wayneashleyberry** [comment]
I've been using `--skip-verify` @dclayton-godaddy
