### ISSUE TITLE
tartufo crashes scanning local repo with no remote named origin

### ISSUE THREAD

**Issue by jakeswenson** [godaddy/tartufo#203]
## 🐛 Bug Report

When running `tartufo scan-local-repo .` it crashes since I don't have a remote named `origin` (I don't use standard remote names for my repositories.)

```bash
❯ tartufo scan-local-repo .
Traceback (most recent call last):
  File "/usr/local/bin/tartufo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tartufo/commands/scan_local_repo.py", line 47, in main
    scanner.scan()
  File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 342, in scan
    for chunk in self.chunks:
  File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 592, in chunks
    self._repo.remotes.origin.fetch()
  File "/usr/local/lib/python3.9/site-packages/git/util.py", line 972, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
```

## To Reproduce

1. clone a git repository and `cd` into the repo directory
2. rename the origin remote. i.e. `git remote rename origin foo`
3. run `tartufo scan-local-repo .`
4. observe error above ^

## Expected Behavior

1. `tartufo` **should not fail** regardless of what the repo's remote names are. 
2. Why does `scan-local-repo` inspect remotes at all?

## Code Example

N/A

## Environment

N/A

**Comment by tarkatronic** [comment]
Fixed in #244
