### ISSUE TITLE
Verbose output doesn't work with new-style entropy exclusions in 2.10

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/tartufo#308]
## 🐛 Bug Report

A scan with verbose output, displaying new-style entropy exclusions, in 2.10 fails

## To Reproduce

Execute
```
tartufo --no-json --verbose --config [myrepo]/tartufo.toml scan-local-repo --no-fetch [myrepo]
```
with a config file that has new-style entropy exclusion and tartufo version 2.10
```
All clear. No secrets detected.

Excluded paths:


Excluded signatures:


Excluded entropy patterns:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/tartufo", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tartufo/cli.py", line 299, in process_issues
    util.echo_result(options, scan, repo_path, output_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tartufo/util.py", line 96, in echo_result
    click.echo("\n".join(options.exclude_entropy_patterns))
TypeError: sequence item 0: expected str instance, Table found
```
## Expected Behavior

The output should be displayed without error

## Environment

```
tartufo --version                                                                                                                             
tartufo, version 2.10.0
```

**Comment by sushantmimani** [comment]
Fixed in #309
