### ISSUE TITLE
Refine the error message when unable to read from remote repository

### ISSUE THREAD

**Issue by sgore-godaddy** [godaddy/tartufo#90]
## Feature Request
Refine the error message when unable to read from remote repository

## Is your feature request related to a problem? Please describe.

If the remote git repository is not reachable due to network issue / VPN connection or Due to remote not being configured correctly, running tartufo scan results in an error like the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/tartufo", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sambhav/Library/Python/3.8/lib/python/site-packages/tartufo/commands/scan_local_repo.py", line 40, in main
    issues = scanner.scan()
  File "/Users/sambhav/Library/Python/3.8/lib/python/site-packages/tartufo/scanner.py", line 188, in scan
    for chunk in self.chunks:
  File "/Users/sambhav/Library/Python/3.8/lib/python/site-packages/tartufo/scanner.py", line 306, in chunks
    branches = self._repo.remotes.origin.fetch()
  File "/Library/Python/3.8/site-packages/git/remote.py", line 797, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/Library/Python/3.8/site-packages/git/remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/Library/Python/3.8/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```

## Describe the solution you'd like

It would be better if tartufo wraps the error and gives a more refined error message when this happens.

## Describe alternatives you've considered

NA

## Teachability, Documentation, Adoption, Migration Strategy

Users would see a more clearer error message and will be able to identify the cause of issue quickly.

**Comment by wayneashleyberry** [comment]
Yeah the same applies to invalid remote ref's

```
Traceback (most recent call last):
  File "/usr/local/bin/tartufo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tartufo/commands/scan_local_repo.py", line 40, in main
    issues = scanner.scan()
  File "/usr/local/lib/python3.8/site-packages/tartufo/scanner.py", line 188, in scan
    for chunk in self.chunks:
  File "/usr/local/lib/python3.8/site-packages/tartufo/scanner.py", line 304, in chunks
    branches = self._repo.remotes.origin.fetch(self.git_options.branch)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 797, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin foo
  stderr: 'fatal: couldn't find remote ref foo'
```

**Comment by tarkatronic** [comment]
@wayneashleyberry What was the command you used to produce this error? I'm assuming it was something along the lines of `tartufo scan-local-repo --branch foo ./repo.git`?

If so, I'm pretty sure my incoming fix will handle this!

**Comment by wayneashleyberry** [comment]
Yeah that looks about right @tarkatronic
